name: qlessproject
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  google_mlkit_barcode_scanning: ^0.14.1
  camera: ^0.11.0
  mobile_scanner: ^5.2.3
  web_socket_channel: ^3.0.0
  upi_pay: ^1.1.0
  qr_flutter: ^4.1.0
  provider: ^6.1.2
  intl: ^0.19.0


  cupertino_icons: ^1.0.8
  google_fonts: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
